services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - cd udagram-api-feed
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed stevenchang219/udagram-api-feed:latest
  - cd ../udagram-api-user
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user stevenchang219/udagram-api-user:latest
  - cd ..
  - docker build -t reverse-proxy -f rp.Dockerfile .
  - docker tag udagram-api-user stevenchang219/reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push stevenchang219/udagram-api-feed
  - docker push stevenchang219/udagram-api-user
  - docker push stevenchang219/reverse-proxy
